### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by Nuxlar** [natebouchat/ReturnsDroneRevive#5]
Wanted to ask if this was still being maintained since I've heard it doesn't work at the moment. If it's not, I also wanted to ask for permission to fix the mod and publish it under another name.

**Comment by Hyenate** [comment]
My apologies, I've been working on other projects as of late and haven't had the time to update this mod.

I do not have any current plans of updating this mod at the moment. If you are interested in working on a fix or expanding this mod, by all means please do! I would love to see this mod fixed and improved down the line. I have no issues with anyone publishing a fix under a different name. Additionally, if you need any help or anything, feel free to let me know and I can see what I can do.
